language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8

install: true
script: mvn test -DskipAssembly

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report -Ptravis-coveralls -DskipAssembly
